import 'package:warehouse_erp/utils/localization/lang_text_constants.dart';

final Map<String, String> zhCN = {
  LangTextConstants.msg_check_delivery_data: "在Tao中检查交货数据",
  // 进入交货页面
  LangTextConstants.msg_enter_delivery_no: "请输入交货单号",
  LangTextConstants.lbl_enter_delivery: "拣货 - 输入交货",
  LangTextConstants.lbl_line_item: "行项目",
  LangTextConstants.lbl_quantity_picked: "拣货数量",
  LangTextConstants.lbl_enter_case_count: "输入箱数",
  LangTextConstants.lbl_scan_pallet_sscc: "扫描托盘SSCC",
  LangTextConstants.lbl_full_pallet: "完整托盘",
  LangTextConstants.lbl_pick_items: "拣货项目",
  LangTextConstants.lbl_com_id: "用户ID",
  LangTextConstants.lbl_login: "登录",
  LangTextConstants.lbl_password: "密码",
  LangTextConstants.lbl_welcome_back: "欢迎\n回来!",
  LangTextConstants.lbl_ok: "确定",
  LangTextConstants.lbl_app_navigation: "应用导航",
  LangTextConstants.msg_check_your_app_s: "通过以下演示屏幕检查您的应用程序UI。",
  LangTextConstants.msg_network_err: "网络错误",

  LangTextConstants.msg_something_went_wrong: "出了点问题！",
  LangTextConstants.lbl_pick: "拣货",
  LangTextConstants.lbl_loading: "加载中",
  LangTextConstants.lbl_picking_options: "拣货选项",
  LangTextConstants.lbl_full_pallet_picking_pick_pallet: "完整托盘拣货 - 拣托盘",
  LangTextConstants.lbl_line_item_no: "行项目号：",
  LangTextConstants.lbl_SKU: "SKU",
  LangTextConstants.lbl_settings: "设置",
  LangTextConstants.lbl_dark_theme: "暗黑主题",
  LangTextConstants.lbl_text_scale: "文本缩放",
  LangTextConstants.lbl_language: "语言",
  LangTextConstants.lbl_back: "返回",
  LangTextConstants.lbl_cancel: "取消",
  LangTextConstants.lbl_transactions: "交易",
  LangTextConstants.lbl_continious_barcode_scanning: "连续条形码扫描",
  LangTextConstants.lbl_color: "颜色",
  LangTextConstants.lbl_save: "保存",
  LangTextConstants.lbl_edit: "编辑",
  LangTextConstants.lbl_materials: "材料",
  LangTextConstants.lbl_inventory: "库存",
  LangTextConstants.lbl_set_urls: "设置应用URL",
  LangTextConstants.msg_Fetchingdataforyou: "正在为您获取数据",
  LangTextConstants.msg_Savingdata: "正在保存数据",
  LangTextConstants.msg_LoginFailedNeedtologinagain: "登录失败，需要重新登录",
  LangTextConstants.msg_Invalidusernameorpassword: "无效的用户名或密码",
  LangTextConstants.msg_Nodatafound: "未找到数据",
  LangTextConstants.msg_url_not_set: "URL未设置",
};
